In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('meal3_cleaned.csv')
df

,meal_name,ingredients,calories_per_serving,carbs,proteins,fats,diet_type,meal_time,serving_size,cost_per_serving_in_inr,region
0,Chole Bhature,"Chickpeas, Refined Flour, Spices, Onion",450,55,15.0,18.0,Vegetarian,breakfast/lunch,1 plate,50,North Indian
1,Aloo Paratha,"Wheat Flour, Potato, Spices, Butter",290,35,6.0,12.0,Vegetarian,breakfast/lunch,1 paratha,25,North Indian
2,Butter Chicken,"Chicken, Butter, Cream, Tomato, Spices",490,18,28.0,32.0,Non-Vegetarian,dinner,1 bowl,80,North Indian
3,Kadhi Pakora,"Besan, Curd, Spices, Onion",260,20,8.0,16.0,Vegetarian,lunch,1 bowl,30,North Indian
4,Litti Chokha,"Wheat Flour, Sattu, Brinjal, Potato, Tomato",360,50,10.0,12.0,Vegetarian,snacks,3 littis with chokha,25,North Indian
...,...,...,...,...,...,...,...,...,...,...,...
483,Oats Porridge,"Oats, Milk, Sugar/Honey",150,25,5.0,3.0,Vegetarian,Breakfast,1 bowl,30,North Indian
484,Sweet Potato Chaat,"Sweet Potato, Spices, Lemon Juice",180,30,3.0,5.0,Vegetarian,Snack,1 bowl,30,North Indian
485,"Fruit Salad (Banana, apple, mango,blueberry)","Banana, apple, mango,blueberry",120,30,2.0,1.0,vegetarian,Snack,1 bowl,60,North Indian
486,Basmati Rice,"Basmati Rice, Water",220,45,5.0,2.0,Vegetarian,Lunch,1 cup cooked,30,North Indian
487,Quinoa Pulao,"Quinoa, Vegetables, Spices",250,35,10.0,8.0,Vegetarian,Lunch,1 bowl,45,North Indian

In [3]:
# Define mappings for meal_time categories
breakfast_keywords = ['breakfast', 'Breakfast', 'Breakfast/Snack', 'breakfast/snacks', 'breakfast/lunch']
lunch_keywords = ['lunch', 'Lunch', 'Lunch/Dinner', 'Lunch/Snack']
dinner_keywords = ['dinner', 'Dinner', 'Lunch/Dinner']
snacks_keywords = ['snacks', 'Snack', 'Snacks', 'Dessert', 'Dessert/Snacks', 'Beverage/Snacks', 'Post-Workout', 'Side Dish', 'salad', 'side dish', 'beverage']
desert_keywords = ['dessert', 'Dessert', 'Dessert/Snacks']

# Function to map meal_time to categories
def map_meal_time(meal_time):
    categories = []
    if isinstance(meal_time, str):  # Check if meal_time is a string
        meal_time_lower = meal_time.lower()
        if any(keyword in meal_time_lower for keyword in breakfast_keywords):
            categories.append('breakfast')
        if any(keyword in meal_time_lower for keyword in lunch_keywords):
            categories.append('lunch')
        if any(keyword in meal_time_lower for keyword in dinner_keywords):
            categories.append('dinner')
        if any(keyword in meal_time_lower for keyword in snacks_keywords):
            categories.append('snacks')
        if any(keyword in meal_time_lower for keyword in desert_keywords):
            categories.append('dessert')

    return categories if categories else ['snacks']  # Default to 'other' if no match

# Apply the mapping to the meal_time column
df['meal_time_categories'] = df['meal_time'].apply(map_meal_time)

In [4]:
df

,meal_name,ingredients,calories_per_serving,carbs,proteins,fats,diet_type,meal_time,serving_size,cost_per_serving_in_inr,region,meal_time_categories
0,Chole Bhature,"Chickpeas, Refined Flour, Spices, Onion",450,55,15.0,18.0,Vegetarian,breakfast/lunch,1 plate,50,North Indian,"[breakfast, lunch]"
1,Aloo Paratha,"Wheat Flour, Potato, Spices, Butter",290,35,6.0,12.0,Vegetarian,breakfast/lunch,1 paratha,25,North Indian,"[breakfast, lunch]"
2,Butter Chicken,"Chicken, Butter, Cream, Tomato, Spices",490,18,28.0,32.0,Non-Vegetarian,dinner,1 bowl,80,North Indian,[dinner]
3,Kadhi Pakora,"Besan, Curd, Spices, Onion",260,20,8.0,16.0,Vegetarian,lunch,1 bowl,30,North Indian,[lunch]
4,Litti Chokha,"Wheat Flour, Sattu, Brinjal, Potato, Tomato",360,50,10.0,12.0,Vegetarian,snacks,3 littis with chokha,25,North Indian,[snacks]
...,...,...,...,...,...,...,...,...,...,...,...,...
483,Oats Porridge,"Oats, Milk, Sugar/Honey",150,25,5.0,3.0,Vegetarian,Breakfast,1 bowl,30,North Indian,[breakfast]
484,Sweet Potato Chaat,"Sweet Potato, Spices, Lemon Juice",180,30,3.0,5.0,Vegetarian,Snack,1 bowl,30,North Indian,[snacks]
485,"Fruit Salad (Banana, apple, mango,blueberry)","Banana, apple, mango,blueberry",120,30,2.0,1.0,vegetarian,Snack,1 bowl,60,North Indian,[snacks]
486,Basmati Rice,"Basmati Rice, Water",220,45,5.0,2.0,Vegetarian,Lunch,1 cup cooked,30,North Indian,[lunch]
487,Quinoa Pulao,"Quinoa, Vegetables, Spices",250,35,10.0,8.0,Vegetarian,Lunch,1 bowl,45,North Indian,[lunch]

In [5]:
df.to_csv('meal3_mealTime.csv', index=False)