In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('D:\calorie_RL\data\meal2_cleaned.csv')
df

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\hp\AppData\Local\Temp\ipykernel_5636\1944898003.py:1: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv('D:\calorie_RL\data\meal2_cleaned.csv')

,meal_name,ingredients,calories_per_serving,carbs,proteins,fats,diet_type,meal_time,serving_size,cost_per_serving_in_inr,region
0,Rajma Chawal,"Kidney Beans, Rice, Tomato, Onion, Garlic, Spices",385,60.0,12.0,8.0,Vegetarian,NaN,1 medium plate,40.0,North Indian
1,Chole Bhature,"Chickpeas, Refined Flour, Spices, Onion",450,55.0,15.0,18.0,Vegetarian,NaN,1 plate,50.0,North Indian
2,Aloo Paratha,"Wheat Flour, Potato, Spices, Butter",290,35.0,6.0,12.0,Vegetarian,NaN,1 paratha,25.0,North Indian
3,Palak Paneer,"Spinach, Paneer, Onion, Tomato, Spices",300,14.0,16.0,18.0,Vegetarian,NaN,1 bowl,45.0,North Indian
4,Butter Chicken,"Chicken, Butter, Cream, Tomato, Spices",490,18.0,28.0,32.0,Non-Vegetarian,dinner,1 bowl,80.0,North Indian
...,...,...,...,...,...,...,...,...,...,...,...
670,Sweet Potato Chaat,"Sweet Potato, Spices, Lemon Juice",180,30.0,3.0,5.0,Vegetarian,Snack,1 bowl,30.0,North Indian
671,"Fruit Salad (Banana, apple, mango,blueberry)","Banana, apple, mango,blueberry",120,30.0,2.0,1.0,vegetarian,Snack,1 bowl,60.0,North Indian
672,Basmati Rice,"Basmati Rice, Water",220,45.0,5.0,2.0,Vegetarian,Lunch,1 cup cooked,30.0,North Indian
673,Quinoa Pulao,"Quinoa, Vegetables, Spices",250,35.0,10.0,8.0,Vegetarian,Lunch,1 bowl,45.0,North Indian
674,Whey Protein Shake,"Whey Protein, Milk/Water",150,5.0,25.0,2.0,Vegetarian,Post-Workout,1 shake,50.0,North Indian

In [3]:
def create_diet_plan(diet_type, total_calories_required, total_budget):
    # Filter meals based on diet type
    filtered_meals = df[df['diet_type'] == diet_type].copy()

    # Sort meals by cost per serving and calories per serving (ascending order)
    filtered_meals.sort_values(by=['cost_per_serving_in_inr', 'calories_per_serving'], inplace=True)

    # Initialize variables
    diet_plan = []
    total_calories = 0
    total_cost = 0

    # Iterate through the meals to create the diet plan
    for _, meal in filtered_meals.iterrows():
        if total_calories >= total_calories_required - 100:
            break  # Stop if calorie requirement is met within the range

        # Calculate the number of servings needed to meet the calorie requirement
        remaining_calories = total_calories_required - total_calories
        servings = min(2, max(1, round(remaining_calories / meal['calories_per_serving'])))

        # Calculate the cost and calories for the selected servings
        meal_calories = servings * meal['calories_per_serving']
        meal_cost = servings * meal['cost_per_serving_in_inr']

        # Check if adding this meal exceeds the budget
        if total_cost + meal_cost > total_budget:
            continue  # Skip this meal if it exceeds the budget

        # Add the meal to the diet plan
        diet_plan.append({
            'meal_name': meal['meal_name'],
            'servings': servings,
            'calories': meal_calories,
            'cost': meal_cost
        })

        # Update total calories and cost
        total_calories += meal_calories
        total_cost += meal_cost

    # Check if the calorie requirement is met
    if total_calories < total_calories_required - 100:
        return "Unable to create a diet plan within the given budget and calorie constraints."

    # Return the diet plan as a DataFrame
    return pd.DataFrame(diet_plan)

In [5]:

diet_type = 'Vegetarian'
total_calories_required = 2000
total_budget = 300

diet_plan = create_diet_plan(diet_type, total_calories_required, total_budget)
print(diet_plan)

        meal_name  servings  calories  cost
0           Papad         2       100  10.0
1           Papad         2       100  10.0
2         Chapati         2       160  10.0
3   Tandoori Roti         2       200  16.0
4         Sandige         2        80  20.0
5            Idli         2       100  20.0
6           Kanji         2       100  20.0
7           Rasam         2       100  20.0
8            Idli         2       100  20.0
9           Kanji         2       100  20.0
10          Rasam         2       100  20.0
11        Papadum         2       100  20.0
12          Rasam         2       100  20.0
13        Chapati         2       200  20.0
14  Tandoori Roti         2       240  20.0
15         Samosa         1       150  10.0